#@ load("@ytt:data", "data")
---
fullName:
  name: #@ data.values.name_prefix + 'allow-all-ingress-to-web-apps'
spec:
  input:
    toPodLabels:
    - key: app-tier
      value: web-app
  recipe: allow-all-to-pods
  recipeVersion: v1
  type: network-policy
  namespaceSelector:
    matchExpressions:
    - key: #@ data.values.label_namespace + "tenant"
      operator: Exists

